### PR TITLE
strip whitespace of element text

### LINKED ISSUE #19: exception due to whitespace in text of tags
For example, whitespace in `relatedStateVariable` tag

```
<argument xmlns="urn:schemas-upnp-org:service-1-0">
		    <name>pairingDeviceID</name>
                    <direction>in</direction>
                    <relatedStateVariable>
                       A_ARG_TYPE_pairingDeviceID
                    </relatedStateVariable>
		</argument>
```

causes `KeyError` when its text is used as key (see [upnpclient/upnp.py#L300](https://github.com/flyte/upnpclient/blob/3f478bc08cee2697650b8dff78348e45fce93ec6/upnpclient/upnp.py#L300))

```
arg_statevar = self.statevars[findtext('relatedStateVariable')]
```

since it contains whitespace. Similar issues occur if text of other tags is used with whitespace.

### PR DESCRIPTION
**Pull request by maiermic**
Fixes #19

### CODE REVIEW

**Comment by maiermic** [comment]
Travis build does **not** fail due to these changes, but because of #21 and #22.

**Comment by flyte** [comment]
Hi @maiermic 
Thanks for your contributions - I'm currently on holiday, so I'll have to check this out (and all of the other issues) once I get back in a week and a bit.
Cheers

**Comment by flyte** [comment]
Thanks! Sorry it took ages.

**Comment by maiermic** [comment]
Never mind. It doesn't always go as planned. Thanks for taking the time. I appreciate it :slightly_smiling_face:

**Pull request merged**
